### ISSUE TITLE
Starting a service with service.start(block=True) makes the caller process delete the pid

### ISSUE THREAD

**Issue by dralves** [torfsen/service#10]
platform=macos
version=0.5.1

The logic on service.start() seems to rely on the caller process dying really fast, before the daemon calls self.pid_file.acquire(). If this doesn't happen (for instance because the caller does some more work or because block=True) then, when the caller dies and the automated cleanup kicks in, the caller will delete the pid file after the daemon calls self.pid_file.acquire() and the file gets deleted without being recreated.

**Comment by torfsen** [comment]
Thanks for your report, @dralves!

I'm not sure whether I understand you correctly: in particular, which automated cleanup are you referring to? There are only two places in the code where a previously created PID file is removed:

- [when `Service.run` has finished](https://github.com/torfsen/service/blob/5cfe2aae2f4521485f2c7baf8bbdda2ef80f26de/src/service/__init__.py#L414).
- [when `Service.is_running` encounters a PID file but no corresponding process exists](https://github.com/torfsen/service/blob/5cfe2aae2f4521485f2c7baf8bbdda2ef80f26de/src/service/__init__.py#L244). Since the PID file stores the daemon's PID this should not be influenced by the caller process exiting.

**Comment by dralves** [comment]
PidFile (the one from pypi "pid"), on create(),  registers a callback to be executed on process exit (line 185 of https://github.com/trbs/pid/blob/master/pid/__init__.py). This makes both the coordinator process (the one that starts the daemon process) and the daemon process race to delete this file. If the coordinator process dies fast, before the daemon process executes self.pid_file.acquire() ( https://github.com/torfsen/service/blob/5cfe2aae2f4521485f2c7baf8bbdda2ef80f26de/src/service/__init__.py#L404) then it's ok, the coordinator deletes the file but the daemon process re-creates it after that and the file persists. If, on the other hand, the coordinator takes a bit of time to die, or blocks until the daemon is running, then it will delete the file from underneath the daemon process and the file gets deleted.

**Comment by torfsen** [comment]
Finally found time to fix this. Thanks again, @dralves, for the detailed report!

**Comment by torfsen** [comment]
Fix released in version [0.5.2](https://github.com/torfsen/service/releases/tag/v0.5.2).
