### ISSUE TITLE
[Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by beesMMS** [torfsen/service#9]
I started using this library some weeks ago and now I face an issue with an Adafruit Library for an I2C sensor. After some research I found out it is happens due to no TTY attached:
`File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO/smbus.py", line 143, in _select_device#012    ioctl(self._device.fileno(), I2C_SLAVE, addr & 0x7F)#012IOError: [Errno 25] Inappropriate ioctl for device`

Does or will the service library provide the option to specify sys.stdin/stdout/stderr as parameter, so the error can be avoided?

**Comment by torfsen** [comment]
Usually, [daemons should not have an attached TTY](https://stackoverflow.com/a/8777697/857390). Hence, you should probably use other streams instead of a TTY's STDIN/STDOUT/STDERR -- a common choice are file handles and named pipes. Ideally you would set them up in [`Service.run`](http://python-service.readthedocs.io/en/stable/#service.Service.run). If you need to set them up before that then make sure to list the handles in [`Service.files_preserve`](http://python-service.readthedocs.io/en/stable/#service.Service.files_preserve), otherwise they will automatically be closed when the service daemonizes.

I'm going to close this issue, but I'm not sure if this approach works for your problem -- if it doesn't, feel free to add more details about your situation and I'll reopen the ticket.
